namespace Assets.Systems.Items
{
    /// <summary>
    /// This class relates Items and the respective amount to be dropped in a single entity.    
    /// Instances of this class are generated by the LootTable class, in the method GetLootFromLootTable()
    /// and are consumed by the LootDropper class.
    /// </summary>
    public class LootItem
    {
        public ItemCode Code { get; set; }
        public int Amount { get; set; }

        public LootItem(ItemCode code, int amount)
        {
            this.Code = code;
            this.Amount = amount;
        }
    }
}
